#waiting for ansible 2.0
#- name: Create DNS zones for site
#  route53_zone: >
#    zone="{{ item.0.zone }}"
#    state="{{ item.0.state }}"
#    comment="{{ item.0.comment }}"
#  with_dict: dns
#  with_subelements:
#    - dns

---
- name: Load in dns specific vars
  include_vars: "{{ vars_file }}"

#    alias="{{ item.1.alias | default(none) }}"
#    alias_hosted_zone_id="{{ item.1.aliashostedzoneid | default(none) }}"

# Loop through the dns object variable (see README.md)
- name: Create DNS entries for site
  route53: >
    command=create 
    aws_access_key="{{ aws_secrets_access_key | default(none) }}"
    aws_secret_key="{{ aws_secrets_secret_key | default(none) }}"
    zone="{{ item.0.zone }}"
    record="{{ item.1.record }}"
    type="{{ item.1.type }}"
    ttl="{{ item.1.ttl }}"
    value="{{ item.1.value }}"
    overwrite=yes
  with_dict: dns
  with_subelements:
    - dns
    - entries
